### ISSUE TITLE
normalization of user sessions on the page

### ISSUE THREAD

**Issue by Angelo0487** [Angelo0487/prueba#2]
It is requested to be able to normalize the use of session within the pages which should allow the user to remain registered while browsing within them.

**Comment by Elahas91** [comment]
Bueno para este problema, propongo hacer que la pagina al inicio, tengo la solicitud de que la session debe estar activa o sino, no se mostrará el contenido y en su lugar mostrará que se debe iniciar sesión y mostrar un botón que guíe de vuelta a el login.

**Comment by Elahas91** [comment]
Se puede implementar al inicio de cada archivo el código, o crear un archivo llamado "sesion.php" el cual tendría el código y sería requerido al inicio del resto de archivos.

**Comment by Elahas91** [comment]
<?php
session_start();
if (!isset($_SESSION['email']) || $_SESSION['email'] === 'Visitante') {
    echo "<p>Para ver el contenido primero debes iniciar sesión.</p>";
    echo "<button onclick=\"window.location.href='login.php'\">Iniciar Sesión</button>";
    exit;
}

**Comment by Elahas91** [comment]
![imagen](https://github.com/user-attachments/assets/d41c46c5-9bfd-4701-b5cc-42f993caca69)

**Comment by Angelo0487** [comment]
me parece adecuada la solución propuesta  para las sesión de usuario en las paginas
